### ISSUE TITLE
What to do with headers?

### ISSUE THREAD

**Issue by deaddev** [comex/star#3]
so the readme says
1. config/config.py iPhone2,1_4.0.1
2. make
3. fix the places where you need to copy headers from OS X and I fail at documentation, goto 4

But what do you mean by number 5 and copy headers from OS X?

Thanks guys

**Comment by comex** [comment]
Try making and note where it fails due to missing headers.

**Comment by deaddev** [comment]
ok i believe i fixed the headers and now i get this

ld: warning: in /var/sdk/usr/lib/dylib1.o, file was built for armv6 which is not the architecture being linked (armv7)
ld: symbol dyld_stub_binding_helper not defined (usually in crt1.o/dylib1.o/bundle1.o)
collect2: ld returned 1 exit status
lipo: can't open input file: /var/folders/x9/x9mQ-KuPG2GoQi+VrrUCrk+++TI/-Tmp-//ccvs1h1N.out (No such file or directory)
make[1]: **\* [install.dylib] Error 1
make: **\* [all] Error 2

it happens at the make for "install"
