### ISSUE TITLE
I need help!!!

### ISSUE THREAD

**Issue by Yell0wra1n** [comex/star#4]
how to do i make a pdf of the files and what website should i use to upload the pdf? PLEASE HELP ME!!! SOMEONE, ANYONE!!!!

**Comment by comex** [comment]
This is not a bug. :<

**Comment by Yell0wra1n** [comment]
I REALLY NEED HELP COMEX!!! HOW DO I PUT THE JAILBREAK ONLINE, COULD YOU LIKE HELP ME BUILD THE WEBSITE. COULD YOU PUT THE FILES ON IT FOR ME? OR JUST WALK ME THROUGH STEP BY STEP, AND WHAT WEBSITE BUILDER DID YOU USE??? PLEASE HELP ME I AM SO FRUSTRATED!!!

**Comment by comex** [comment]
Why do you want to do this?

**Comment by xhan** [comment]
seems github need provide a "helloworld" programming test before user's register.

**Comment by Yell0wra1n** [comment]
I REALLY WANT TO BECAUSE I WANT TO UNDERSTAND HOW THIS IS DONE. PLEASE HELP ME I BEG YOU
